name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yuvalost/dockerworkshop:${{ github.run_number }}
    - name: Login to Docker Hub
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $PASSWORD | docker login -u $USERNAME --password-stdin
    - name: Push the image
      run: docker push yuvalost/dockerworkshop:${{ github.run_number }}
